## Problems on arrays

In [44]:
import numpy as np
import sys

In [45]:
arr = np.random.randint(100,size=(10))
arr

array([38, 83, 74, 33, 50, 65, 50, 70, 18, 49])

In [46]:
def display_complexity(tc="", sc=""):
    print(f"TC: O({tc})")
    print(f"SC: O({sc})\n")

## Find the smallest element in an array

In [47]:
# Method 1: sort array in ascending order number at 0th position is smallest element
smallest = list(sorted(arr))[0]
print(f"Smallest: {smallest}")
display_complexity("nlogn","1")

# Method 2: using a min variable updating it when new mininum is encountered
mini = sys.maxsize
for num in arr:
    if num<mini:
        mini = num
print(f"Smallest: {mini}")
display_complexity("n","1")

Smallest: 18
TC: O(nlogn)
SC: O(1)

Smallest: 18
TC: O(n)
SC: O(1)



## Find the largest number in an array

In [48]:
# Method 1: sort array in ascending order number at (array length-1)th position is largest element
largest = list(sorted(arr))[-1]
print(f"largest: {largest}")
display_complexity("nlogn","1")

# Method 2: using a max variable updating it when new mininum is encountered
maxi = -sys.maxsize
for num in arr:
    if num>maxi:
        maxi = num
print(f"largest: {maxi}")
display_complexity("n","1")

largest: 83
TC: O(nlogn)
SC: O(1)

largest: 83
TC: O(n)
SC: O(1)



## Second Smallest and Second Largest element in an array

In [49]:
# Method 1: Sorting
# Sort the array in ascending order
# The element present at the second index is the second smallest element
# The element present at the second index from the end is the second largest element
# Does not work if the array contains duplicates
second_smallest = list(sorted(arr))[1] if len(arr)>1 else list(sorted(arr))[0]
print(f"Second smallest: {second_smallest}")
second_largest = list(sorted(arr))[-2] if len(arr)>1 else list(sorted(arr))[0]
print(f"Second largest: {second_largest}")
display_complexity("nlogn","1")

# Method 2: Using Two traversals
# Find the smallest and largest element in the array in a single traversal
# After this, we once again traverse the array and find an element that is just greater than the smallest element we just found.
# Similarly, we would find the largest element which is just smaller than the largest element we just found
# Indeed, this is our second smallest and second largest element.

maxi = -sys.maxsize
mini = sys.maxsize
for num in arr:
    maxi = max(maxi,num)
    mini = min(mini,num)

maximum = maxi
minimum = mini
maxi = -sys.maxsize
mini = sys.maxsize
for num in arr:
    if maxi<num and num!=maximum:
        maxi = num
    if mini>num and num!=minimum:
        mini = num
    
print(f"Second smallest: {mini}")
print(f"Second largest: {maxi}")
display_complexity("n","1")

# Method 3: Using single traversal and smart comparison
# Approach:
# We would require four variables: small,second_small, large, and second_large. Variable small and second_small are initialized to INT_MAX while large and second_large are initialized to INT_MIN.

# Second Smallest Algo:

# If the current element is smaller than ‘small’, then we update second_small and small variables
# Else if the current element is smaller than ‘second_small’ then we update the variable ‘second_small’
# Once we traverse the entire array, we would find the second smallest element in the variable second_small.
# Here’s a quick demonstration of the same.
# Second Largest Algo:

# If the current element is larger than ‘large’ then update second_large and large variables
# Else if the current element is larger than ‘second_large’ then we update the variable second_large.
# Once we traverse the entire array, we would find the second largest element in the variable second_large.
# Here’s a quick demonstration of the same.

maxi = -sys.maxsize
mini = sys.maxsize
second_maxi = -sys.maxsize
second_mini = sys.maxsize
for num in arr:
    if num>maxi:
        second_maxi = maxi
        maxi = num
    elif num>second_maxi and num!=maxi:
        second_maxi = num
    if num<mini:
        second_mini = mini
        mini = num
    elif num<second_mini and num!=mini:
        second_mini = num
print(f"Second smallest: {second_mini}")
print(f"Second largest: {second_maxi}")
display_complexity("n","1")

Second smallest: 33
Second largest: 74
TC: O(nlogn)
SC: O(1)

Second smallest: 33
Second largest: 74
TC: O(n)
SC: O(1)

Second smallest: 33
Second largest: 74
TC: O(n)
SC: O(1)



## Reverse a given array

In [50]:
# Method 1: Two pointers approach
start = 0
end = len(arr)-1
while start<end:
    arr[start],arr[end]=arr[end],arr[start]
    start+=1
    end -=1
print(arr)
display_complexity("n","1")

# Method 2: Built in function
print(list(reversed(arr)))
display_complexity("n","1")

[49 18 70 50 65 50 33 74 83 38]
TC: O(n)
SC: O(1)

[38, 83, 74, 33, 50, 65, 50, 70, 18, 49]
TC: O(n)
SC: O(1)



## Count frequency of each element in an array

In [51]:
# Method 1: Using hashmap
hmap = {}
for num in arr:
    hmap[num] = hmap.get(num,0)+1

print(hmap)
display_complexity("n","n")

{49: 1, 18: 1, 70: 1, 50: 2, 65: 1, 33: 1, 74: 1, 83: 1, 38: 1}
TC: O(n)
SC: O(n)



## Rearrange array in increasing-decreasing order

In [52]:
# Method 1
# Sort the whole array. Then print the first half of the array to get the first half in 
# the ascending order and then print the rest of the array in the reverse order.

sorted_arr = sorted(arr)
mid = len(sorted_arr)//2
print(sorted_arr[:mid],end="")
print(sorted_arr[mid:][::-1])
print("TC: O(nlogn)+O(n) * O(nlogn)")
print("SC: O(1)")

[18, 33, 38, 49, 50][83, 74, 70, 65, 50]
TC: O(nlogn)+O(n) * O(nlogn)
SC: O(1)


## Calculate sum of the elements of the array

In [53]:
summation = 0
for num in arr:
    summation+=num
print(summation)
display_complexity("n","1")

530
TC: O(n)
SC: O(1)



## Rotate array by K elements – Block Swap Algorithm

In [54]:
k = 2
print(arr)
array = arr.copy()
array = [1,2,3,4,5,6,7]
n = len(array)
def swap(src_ind,dest_ind,size):
    for i in range(size):
        array[src_ind+i],array[dest_ind+i]=array[dest_ind+i],array[src_ind+i]

def block_swap(array,i,k,n):
    if k==0 or k==n:
        return
    if k==n-k:
        swap(i,k+i,k)
        return
    elif k<n-k:
        swap(i,n-k+i,k)
        block_swap(array,i,k,n-k)
    else:
        swap(i,k,n-k)
        block_swap(array,n-k+i,2*k-n,k)

block_swap(array,0,k,n)
print(array)

[49 18 70 50 65 50 33 74 83 38]
[3, 4, 5, 6, 7, 1, 2]


In [55]:
# Method 2: Reversal Algorithm
array = [1,2,3,4,5,6,7]
def reverse(array,start,end):
    while start<end:
        array[start],array[end]=array[end],array[start]
        start+=1
        end-=1
k = 2
k -= 1
print(array)
n = len(array)-1
reverse(array,0,k)
reverse(array,n-k+1,n)
# reverse(array,0,n-k-1)
# reverse(array,n-k,n)
reverse(array,0,n)
print(array)

[1, 2, 3, 4, 5, 6, 7]
[7, 6, 5, 4, 3, 1, 2]


## Average of all elements in an array

In [56]:
avg = 0
summation = 0
for num in arr:
    summation+=num
avg = summation/len(arr)
print(avg)

53.0


## Find the median of the given array

In [57]:
median = 0
is_odd = True if len(arr)%2==1 else False
mid = len(arr)//2
sorted_arr = sorted(arr)
if is_odd:
    median = sorted_arr[mid]
else:
    median = (sorted_arr[mid]+sorted_arr[mid-1])/2
print(median)
display_complexity("nlogn","1")              

50.0
TC: O(nlogn)
SC: O(1)



## Remove Duplicates in-place from Sorted Array

In [88]:
# Method 1: using hashing
s = set()
array = arr.copy()
array = [12,12,656,3,56,56,65,656,65,5]
i = 0
for ind,num in enumerate(array):
    if not num in s:
        s.add(num)
        array[i] = num
        i+=1
    else:
        array[i] = 0
print(i)
n = len(array)
for idx in range(i,n):
    array[idx] = 0
print(array)
print(s)
print("---------------------------")
# Method 2:  Two pointers
array = [1,1,2,3,3,4,5,6,7,8]
i = 0
for j in range(1,n):
    if array[i]!=array[j]:
        i+=1
        array[i] = array[j]
print(i+1)
print(array)
    

6
[12, 656, 3, 56, 65, 5, 0, 0, 0, 0]
{65, 3, 5, 12, 656, 56}
---------------------------
8
[1, 2, 3, 4, 5, 6, 7, 8, 7, 8]
